# =============================================================================
# decision_tree.py
# SHRMS — Intelligent Workflow Routing
# Decision Tree Algorithm — IPCR Evaluation Form + Leave Application
#
# WHAT THIS FILE IS:
#   Layer 2 of the Intelligent Workflow Routing system.
#   A trained ML Decision Tree classifier for IPCR form routing.
#
# ACADEMIC BASIS:
#   Reference [7] Charbuty & Abdulazeez (2021):
#     "Classification Based on Decision Tree Algorithm for Machine Learning"
#     → Defines Decision Tree as a supervised ML classification model.
#     → Mentions pruning (max_depth) as a technique to prevent overfitting.
#
#   Reference [8] Bansal et al. (2022):
#     Comparative ML analysis confirming DT's reliability for classification.
#
# HOW IT WORKS:
#   1. Load the training CSV generated by training_data.py
#   2. Split into 70% training / 10% validation / 20% test
#   3. Train a DecisionTreeClassifier on the training set
#   4. Evaluate on validation set (training check) and test set (final)
#   5. Run k-Fold Cross-Validation for additional overfitting assurance
#   6. Save the trained model to disk as a .pkl file
#
# SPLIT RATIONALE (70/20/10):
#   Training set (70%) — used to fit the Decision Tree
#   Validation set (10%) — checks generalisation before final test
#   Test set (20%) — held back completely, used only for final evaluation
#   With 900 total records: 630 training / 90 validation / 180 test
#
# OVERFITTING PREVENTION — FOUR LAYERS:
#
#   Layer 1 — max_depth=4 (Pruning)
#     Limits the tree to 4 levels. Without this, the tree can grow
#     until every training record is its own leaf — perfect on training
#     data but useless on new data. This is the primary structural guard.
#     Referenced directly in the thesis under "Pruning."
#
#   Layer 2 — min_samples_leaf=5 (Leaf Sample Guard)
#     A leaf node is only created if it contains at least 5 training
#     samples. This prevents the tree from making decisions based on
#     tiny, unrepresentative pockets of training data.
#
#   Layer 3 — Train-Validation Gap Check (70/20/10 split)
#     Training accuracy is compared against validation accuracy after
#     fitting. A gap > 5% triggers a warning. A gap near 0% confirms
#     the model generalises — it did not simply memorise training data.
#
#   Layer 4 — k-Fold Cross-Validation (k=5)
#     The training set is divided into 5 equal folds. The model is
#     trained 5 times, each time on 4 folds and tested on the 5th.
#     This produces 5 independent accuracy scores. We report:
#       - Mean cross-val accuracy  (should be close to test accuracy)
#       - Standard deviation       (low std = stable, not lucky)
#     High mean + low std confirms accuracy is consistent across
#     different subsets of data, not a one-time lucky split result.
#
# THESIS TERMINOLOGY USED HERE:
#   Root node     → the very first split/question the tree asks
#   Decision node → an internal node representing one condition
#   Leaf node     → a terminal node — the final predicted routing action
#   Splitting     → dividing records at a node using a feature condition
#   Pruning       → max_depth limits tree depth to prevent overfitting
#   Entropy       → splitting criterion used here (Information Gain)
#
# THE THREE OUTPUT CLASSES (leaf nodes):
#   0 → route_to_evaluator    (fresh form — send to assigned evaluator)
#   1 → return_for_remarks    (rating < 2.5 — evaluator must add remarks)
#   2 → save_data              (rating >= 2.5 — passed, save directly)
# =============================================================================

import os
import pickle
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier, export_text, plot_tree # Added the 'plot_tree' to visualize the tree
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import classification_report, accuracy_score

# Added to visualize the tree
import matplotlib.pyplot as plt


from org_and_rules import (
    IPCR_FEATURES, IPCR_DT_ACTIONS,
    LEAVE_FEATURES, LEAVE_DT_ACTIONS,
)

# Resolve all file paths relative to this script's location
BASE_DIR = os.path.dirname(os.path.abspath(__file__))


class IPCRDecisionTree:
    """
    Trained Decision Tree classifier for IPCR form routing.

    Input features (from org_and_rules.IPCR_FEATURES):
        role_encoded         — employee's role as an integer
        performance_rating   — IPCR score 1.0–5.0 (0.0 if first submission)
        is_first_submission  — 1 = fresh form, 0 = returning form

    Output classes (leaf nodes):
        0 → route_to_evaluator
        1 → return_for_remarks
        2 → save_data

    Overfitting prevention (four layers):
        1. max_depth=4          — structural pruning
        2. min_samples_leaf=5   — leaf sample guard
        3. train-val gap check  — 70/20/10 split comparison
        4. k-Fold CV (k=5)      — stability check across 5 data subsets
    """

    MODEL_PATH = os.path.join(BASE_DIR, "models", "ipcr_dt.pkl")

    def __init__(self):
        self.model = None

    # =========================================================================
    # TRAIN
    # =========================================================================

    def train(self):
        """
        Loads training CSV and trains the Decision Tree classifier.
        Runs four layers of overfitting assurance and prints a full report.

        Step 1 — Load training data from CSV
        Step 2 — Separate features (X) from labels (y)
        Step 3 — Split into 70% train / 10% validation / 20% test
        Step 4 — Create and train the DecisionTreeClassifier
        Step 5 — Train-Validation gap check (Layer 3)
        Step 6 — Test set evaluation (final accuracy)
        Step 7 — k-Fold Cross-Validation (Layer 4)
        Step 8 — Print the human-readable tree structure
        Step 9 — Save the trained model to disk
        """

        csv_path = os.path.join(BASE_DIR, "data", "ipcr_training_data.csv")

        # ------------------------------------------------------------------
        # Step 1: Load the training CSV
        # Generated by training_data.py (Task 3) — 900 records total
        # ------------------------------------------------------------------
        df = pd.read_csv(csv_path)

        # ------------------------------------------------------------------
        # Step 2: Separate features (X) and labels (y)
        # X = inputs the tree uses to make decisions
        # y = correct answers the tree must learn to predict
        # ------------------------------------------------------------------
        X = df[IPCR_FEATURES]       # role_encoded, performance_rating, is_first_submission
        y = df["routing_action"]    # 0, 1, or 2

        # ------------------------------------------------------------------
        # Step 3: 70/20/10 train-test-validation split
        #
        # We split in two stages:
        #
        # Stage A — split the full dataset into 80% temp and 20% test
        #   The test set (20%) is held back completely until Step 6.
        #   It is never seen during training or validation.
        #
        # Stage B — split the 80% temp into 70% train and 10% validation
        #   train = 70% of total (630 rows)
        #   val   = 10% of total (90 rows)
        #
        # Why two stages?
        #   train_test_split only splits into two parts at a time.
        #   To get three parts (train/val/test) we apply it twice.
        #
        # random_state=42 ensures reproducibility — same split every run.
        # ------------------------------------------------------------------

        # Stage A: separate test set (20% of total = 180 rows)
        X_temp, X_test, y_temp, y_test = train_test_split(
            X, y,
            test_size=0.20,
            random_state=42
        )

        # Stage B: split remaining 80% into train (70%) and validation (10%)
        # val_size = 0.10 / 0.80 = 0.125
        # Because we are splitting 80% of the data, 12.5% of that 80%
        # equals exactly 10% of the original total.
        X_train, X_val, y_train, y_val = train_test_split(
            X_temp, y_temp,
            test_size=0.125,
            random_state=42
        )

        # ------------------------------------------------------------------
        # Step 4: Create and train the DecisionTreeClassifier
        #
        # OVERFITTING PREVENTION — LAYER 1: max_depth=4
        #   Structural pruning. Caps the tree at 4 decision levels.
        #   Without this, the tree grows until every training sample is
        #   its own leaf — perfect training accuracy, terrible on new data.
        #   Cited in thesis under "Pruning" [7].
        #
        # OVERFITTING PREVENTION — LAYER 2: min_samples_leaf=5
        #   Leaf sample guard. A leaf node (final decision) is only allowed
        #   if it is supported by at least 5 training samples.
        #   Prevents the tree from making routing decisions based on tiny,
        #   unrepresentative pockets of training data (e.g., one outlier
        #   record that happened to have an unusual feature combination).
        #
        # criterion="entropy"
        #   Uses Information Gain to decide how to split nodes.
        #   Referenced in thesis under "Splitting Criteria".
        #
        # random_state=42
        #   Reproducible training — same tree structure every run.
        # ------------------------------------------------------------------
        self.model = DecisionTreeClassifier(
            criterion="entropy",
            max_depth=4,            # Layer 1: structural pruning
            min_samples_leaf=5,     # Layer 2: leaf sample guard
            random_state=42
        )

        self.model.fit(X_train, y_train)
        # ↑ The tree learns here — builds its structure from X_train/y_train

# for additional validation that the tree is not overfitting
        print("\n[ Tree Structure Info ]")
        print("Tree depth:", self.model.get_depth())
        print("Number of leaves:", self.model.get_n_leaves())
        print()

        # ------------------------------------------------------------------
        # Step 5: Train-Validation gap check
        #
        # OVERFITTING PREVENTION — LAYER 3
        # Compare training accuracy vs validation accuracy.
        # A gap > 5% signals overfitting.
        # A gap near 0% confirms the model generalises to unseen data.
        # ------------------------------------------------------------------
        y_train_pred   = self.model.predict(X_train)
        train_accuracy = accuracy_score(y_train, y_train_pred)

        y_val_pred   = self.model.predict(X_val)
        val_accuracy = accuracy_score(y_val, y_val_pred)

        gap = train_accuracy - val_accuracy

        # ------------------------------------------------------------------
        # Step 6: Test set evaluation (final, definitive evaluation)
        # The test set was never seen during training or validation.
        # ------------------------------------------------------------------
        y_test_pred   = self.model.predict(X_test)
        test_accuracy = accuracy_score(y_test, y_test_pred)

        # ------------------------------------------------------------------
        # Step 7: k-Fold Cross-Validation (k=5)
        #
        # OVERFITTING PREVENTION — LAYER 4
        #
        # The training set (630 rows) is split into 5 equal folds of
        # 126 rows each. The model is trained and evaluated 5 independent
        # times, rotating which fold is used as the test set each time.
        #
        # This produces 5 independent accuracy scores. We report:
        #   Mean — expected performance across all data subsets
        #   Std  — consistency (low std = stable, not erratic)
        #
        # WHY THIS MATTERS:
        #   A single 70/20/10 split could produce high accuracy if the
        #   random split happened to favour easy test cases.
        #   k-Fold tests the model on every training sample at least once,
        #   making it a much stronger proof of generalisation.
        #
        #   If CV mean ≈ test accuracy → test result is trustworthy.
        #   If CV std ≤ 0.03 → model is stable across all subsets.
        # ------------------------------------------------------------------
        cv_scores = cross_val_score(
            self.model, X_train, y_train,
            cv=5,
            scoring="accuracy"
        )
        cv_mean = np.mean(cv_scores)
        cv_std  = np.std(cv_scores)

        # ------------------------------------------------------------------
        # Print full overfitting assurance report
        # ------------------------------------------------------------------
        print("=" * 65)
        print("  IPCR Decision Tree — Training & Overfitting Assurance Report")
        print("=" * 65)
        print()
        print("  [ Dataset ]")
        print(f"    Total records     : {len(df)}")
        print(f"    Split             : 70% train / 10% validation / 20% test")
        print(f"    Training samples  : {len(X_train)}")
        print(f"    Validation samples: {len(X_val)}")
        print(f"    Test samples      : {len(X_test)}")
        print()

        print("  [ Overfitting Prevention — 4 Layers ]")
        print()

        # Layer 1
        print("  LAYER 1 — Structural Pruning (max_depth=4)")
        print(f"    Tree depth used   : {self.model.get_depth()}")
        print(f"    Max allowed depth : 4")
        if self.model.get_depth() < 4:
            print(f"    ✅ Tree did not need full depth — naturally simple.")
        else:
            print(f"    ✅ Tree pruned at depth 4 — unlimited growth prevented.")
        print()

        # Layer 2
        n_leaves = self.model.get_n_leaves()
        print("  LAYER 2 — Leaf Sample Guard (min_samples_leaf=5)")
        print(f"    Number of leaf nodes  : {n_leaves}")
        print(f"    Min samples per leaf  : 5 (enforced by classifier)")
        print(f"    ✅ No leaf created from fewer than 5 training samples.")
        print()

        # Layer 3
        print("  LAYER 3 — Train-Validation Gap Check")
        print(f"    Training accuracy   : {train_accuracy:.4f}  ({train_accuracy:.2%})")
        print(f"    Validation accuracy : {val_accuracy:.4f}  ({val_accuracy:.2%})")
        print(f"    Gap (train - val)   : {gap:.4f}  ({gap:.2%})")
        if gap > 0.05:
            print(f"    ⚠️  Gap exceeds 5% — possible overfitting.")
        else:
            print(f"    ✅ Gap ≤ 5% — model generalises to unseen data.")
        print()

        # Layer 4
        print("  LAYER 4 — 5-Fold Cross-Validation")
        print(f"    CV scores (5 folds): {[round(s, 4) for s in cv_scores]}")
        print(f"    Mean CV accuracy   : {cv_mean:.4f}  ({cv_mean:.2%})")
        print(f"    Std deviation      : {cv_std:.4f}  ({cv_std:.2%})")
        cv_vs_test = abs(cv_mean - test_accuracy)
        if cv_std <= 0.03:
            print(f"    ✅ Low std ({cv_std:.2%}) — stable across all folds.")
        else:
            print(f"    ⚠️  Std ({cv_std:.2%}) > 0.03 — results vary across folds.")
        if cv_vs_test <= 0.05:
            print(f"    ✅ CV mean ({cv_mean:.2%}) ≈ test accuracy ({test_accuracy:.2%})")
            print(f"       Test result is trustworthy — not a lucky split.")
        else:
            print(f"    ⚠️  CV mean and test accuracy differ by {cv_vs_test:.2%}.")
        print()

        # Final test result
        print("  [ Final Test Set Result ]")
        print(f"    Test accuracy: {test_accuracy:.4f}  ({test_accuracy:.2%})")
        print()

        # Classification reports
        print("  Test Set Classification Report:")
        present_labels = sorted(y_test.unique())
        print(classification_report(
            y_test, y_test_pred,
            labels=present_labels,
            target_names=[IPCR_DT_ACTIONS[i] for i in present_labels]
        ))

        print("  Validation Set Classification Report:")
        present_val_labels = sorted(y_val.unique())
        print(classification_report(
            y_val, y_val_pred,
            labels=present_val_labels,
            target_names=[IPCR_DT_ACTIONS[i] for i in present_val_labels]
        ))

        # ------------------------------------------------------------------
        # Step 8: Print the tree structure
        # ------------------------------------------------------------------
        print("  Tree Structure (Root → Decision Nodes → Leaf Nodes):")
        print(export_text(self.model, feature_names=IPCR_FEATURES))

        # ------------------------------------------------------------------
        # Step 9: Save the trained model to disk
        # ------------------------------------------------------------------
        self._save()

    # =========================================================================
    # SAVE
    # =========================================================================

    def _save(self):
        """Saves the trained model to a .pkl file."""
        models_dir = os.path.join(BASE_DIR, "models")
        os.makedirs(models_dir, exist_ok=True)

        with open(self.MODEL_PATH, "wb") as f:
            pickle.dump(self.model, f)

        print(f"  Model saved → {self.MODEL_PATH}\n")

    # =========================================================================
    # LOAD
    # =========================================================================

    def load(self):
        """Loads a previously trained model from disk."""
        if not os.path.exists(self.MODEL_PATH):
            raise FileNotFoundError(
                f"No trained model found at:\n"
                f"  {self.MODEL_PATH}\n"
                f"Fix: run  python setup.py  first."
            )

        with open(self.MODEL_PATH, "rb") as f:
            self.model = pickle.load(f)

    # =========================================================================
    # PREDICT
    # =========================================================================

    def predict(self, features: dict) -> dict:
        """
        Uses the trained Decision Tree to predict the routing action
        for a single IPCR form submission.

        Parameters:
            features (dict) — must contain all keys in IPCR_FEATURES:
                role_encoded         (int)
                performance_rating   (float)
                is_first_submission  (int)

        Returns:
            dict:
                routing_action_code  — int (0, 1, or 2)
                routing_action_label — human-readable string
                confidence_pct       — how confident the tree is (0–100%)
        """

        if self.model is None:
            self.load()

        row = pd.DataFrame([{col: features[col] for col in IPCR_FEATURES}])

        prediction    = self.model.predict(row)[0]
        probabilities = self.model.predict_proba(row)[0]
        confidence    = round(float(max(probabilities)) * 100, 2)

        return {
            "routing_action_code":  int(prediction),
            "routing_action_label": IPCR_DT_ACTIONS[int(prediction)],
            "confidence_pct":       confidence,
        }
    
     # IPCR Decision Tree Visualization
    def visualize(self):
        """ Displays the trained IPCR Decision Tree as a diagram. """
        if self.model is None:
            self.load()

        plt.figure(figsize=(12, 8))
        plot_tree(
            self.model,
            feature_names=IPCR_FEATURES,
            class_names=[IPCR_DT_ACTIONS[i] for i in sorted(IPCR_DT_ACTIONS.keys())],
            filled=True,
            rounded=True,
            fontsize=9
        )
        plt.title("IPCR Decision Tree")
        plt.show()


# =============================================================================
# LEAVE APPLICATION DECISION TREE
# =============================================================================

class LeaveDecisionTree:
    """
    Trained Decision Tree classifier for leave application routing.

    Input features (from org_and_rules.LEAVE_FEATURES):
        leave_type_encoded       — leave type as integer (0–7)
        days_requested           — number of days filed
        has_required_attachment  — 1 if required document attached, 0 if not
        dh_decision              — 0=pending, 1=approved, 2=rejected
        hr_decision              — 0=pending, 1=approved, 2=rejected
        has_rejection_reason     — 1 if rejection reason recorded, 0 if not

    Output classes (leaf nodes):
        0 → route_to_department_head
        1 → route_to_hr
        2 → require_rejection_reason
        3 → completed

    Overfitting prevention (four layers):
        1. max_depth=4          — structural pruning
        2. min_samples_leaf=5   — leaf sample guard
        3. train-val gap check  — 70/20/10 split comparison
        4. k-Fold CV (k=5)      — stability check across 5 data subsets
    """

    MODEL_PATH = os.path.join(BASE_DIR, "models", "leave_dt.pkl")

    def __init__(self):
        self.model = None

    # =========================================================================
    # TRAIN
    # =========================================================================

    def train(self):
        """
        Loads the leave training CSV and trains the Decision Tree classifier.
        Runs four layers of overfitting assurance and prints a full report.

        Step 1 — Load training data from CSV
        Step 2 — Separate features (X) from labels (y)
        Step 3 — Split into 70% train / 10% validation / 20% test
        Step 4 — Create and train the DecisionTreeClassifier
        Step 5 — Train-Validation gap check (Layer 3)
        Step 6 — Test set evaluation (final accuracy)
        Step 7 — k-Fold Cross-Validation (Layer 4)
        Step 8 — Print the human-readable tree structure
        Step 9 — Save the trained model to disk
        """

        csv_path = os.path.join(BASE_DIR, "data", "leave_training_data.csv")

        # ------------------------------------------------------------------
        # Step 1: Load the training CSV
        # Generated by leave_training_data.py — 1,000 records total
        # ------------------------------------------------------------------
        df = pd.read_csv(csv_path)

        # ------------------------------------------------------------------
        # Step 2: Separate features (X) and labels (y)
        # X = inputs the tree uses to make decisions
        # y = correct routing actions the tree must learn to predict
        # ------------------------------------------------------------------
        X = df[LEAVE_FEATURES]      # 7 features from org_and_rules.py
        y = df["routing_action"]    # 0, 1, 2, or 3

        # ------------------------------------------------------------------
        # Step 3: 70/20/10 train-test-validation split
        #
        # Stage A — split full dataset into 80% temp and 20% test
        #   Test set (200 rows) is held back completely until Step 6.
        #
        # Stage B — split 80% temp into 70% train and 10% validation
        #   train = 700 rows  (70% of total)
        #   val   = 100 rows  (10% of total)
        #
        # stratify=y ensures all 4 classes are proportionally represented
        # in every split — critical because label distribution is 25% each.
        # ------------------------------------------------------------------

        # Stage A: separate test set
        X_temp, X_test, y_temp, y_test = train_test_split(
            X, y,
            test_size=0.20,
            random_state=42,
            stratify=y
        )

        # Stage B: split remaining 80% → train (70%) + validation (10%)
        # val_size = 0.10 / 0.80 = 0.125
        X_train, X_val, y_train, y_val = train_test_split(
            X_temp, y_temp,
            test_size=0.125,
            random_state=42,
            stratify=y_temp
        )

        # ------------------------------------------------------------------
        # Step 4: Create and train the DecisionTreeClassifier
        #
        # OVERFITTING PREVENTION — LAYER 1: max_depth=4
        #   Structural pruning. Caps the tree at 4 decision levels.
        #   Cited in thesis under "Pruning" [7].
        #
        # OVERFITTING PREVENTION — LAYER 2: min_samples_leaf=5
        #   Leaf sample guard. A leaf node is only created if it contains
        #   at least 5 training samples.
        #
        # criterion="entropy"
        #   Uses Information Gain to decide how to split nodes.
        #   Referenced in thesis under "Splitting Criteria".
        # ------------------------------------------------------------------
        self.model = DecisionTreeClassifier(
            criterion="entropy",
            max_depth=4,            # Layer 1: structural pruning
            min_samples_leaf=5,     # Layer 2: leaf sample guard
            random_state=42
        )

        self.model.fit(X_train, y_train)
        
        # for additional validation that the tree is not overfitting
        print("\n[ Tree Structure Info ]")
        print("Tree depth:", self.model.get_depth())
        print("Number of leaves:", self.model.get_n_leaves())
        print()

        # ------------------------------------------------------------------
        # Step 5: Train-Validation gap check
        #
        # OVERFITTING PREVENTION — LAYER 3
        # ------------------------------------------------------------------
        y_train_pred   = self.model.predict(X_train)
        train_accuracy = accuracy_score(y_train, y_train_pred)

        y_val_pred   = self.model.predict(X_val)
        val_accuracy = accuracy_score(y_val, y_val_pred)

        gap = train_accuracy - val_accuracy

        # ------------------------------------------------------------------
        # Step 6: Test set evaluation (final, definitive evaluation)
        # ------------------------------------------------------------------
        y_test_pred   = self.model.predict(X_test)
        test_accuracy = accuracy_score(y_test, y_test_pred)

        # ------------------------------------------------------------------
        # Step 7: k-Fold Cross-Validation (k=5)
        #
        # OVERFITTING PREVENTION — LAYER 4
        # ------------------------------------------------------------------
        cv_scores = cross_val_score(
            self.model, X_train, y_train,
            cv=5,
            scoring="accuracy"
        )
        cv_mean = np.mean(cv_scores)
        cv_std  = np.std(cv_scores)

        # ------------------------------------------------------------------
        # Print full overfitting assurance report
        # ------------------------------------------------------------------
        print("=" * 65)
        print("  Leave Application Decision Tree — Training Report")
        print("=" * 65)
        print()
        print("  [ Dataset ]")
        print(f"    Total records     : {len(df)}")
        print(f"    Split             : 70% train / 10% validation / 20% test")
        print(f"    Training samples  : {len(X_train)}")
        print(f"    Validation samples: {len(X_val)}")
        print(f"    Test samples      : {len(X_test)}")
        print()
        print("  [ Label distribution in training set ]")
        for cls, count in sorted(y_train.value_counts().items()):
            print(f"    Class [{cls}] {LEAVE_DT_ACTIONS[cls]:<30}: {count} records")
        print()

        print("  [ Overfitting Prevention — 4 Layers ]")
        print()

        # Layer 1
        print("  LAYER 1 — Structural Pruning (max_depth=4)")
        print(f"    Tree depth used   : {self.model.get_depth()}")
        print(f"    Max allowed depth : 4")
        if self.model.get_depth() < 4:
            print(f"    ✅ Tree did not need full depth — naturally simple.")
        else:
            print(f"    ✅ Tree pruned at depth 4 — unlimited growth prevented.")
        print()

        # Layer 2
        n_leaves = self.model.get_n_leaves()
        print("  LAYER 2 — Leaf Sample Guard (min_samples_leaf=5)")
        print(f"    Number of leaf nodes  : {n_leaves}")
        print(f"    Min samples per leaf  : 5 (enforced by classifier)")
        print(f"    ✅ No leaf created from fewer than 5 training samples.")
        print()

        # Layer 3
        print("  LAYER 3 — Train-Validation Gap Check")
        print(f"    Training accuracy   : {train_accuracy:.4f}  ({train_accuracy:.2%})")
        print(f"    Validation accuracy : {val_accuracy:.4f}  ({val_accuracy:.2%})")
        print(f"    Gap (train - val)   : {gap:.4f}  ({gap:.2%})")
        if gap > 0.05:
            print(f"    ⚠️  Gap exceeds 5% — possible overfitting.")
        else:
            print(f"    ✅ Gap ≤ 5% — model generalises to unseen data.")
        print()

        # Layer 4
        print("  LAYER 4 — 5-Fold Cross-Validation")
        print(f"    CV scores (5 folds): {[round(s, 4) for s in cv_scores]}")
        print(f"    Mean CV accuracy   : {cv_mean:.4f}  ({cv_mean:.2%})")
        print(f"    Std deviation      : {cv_std:.4f}  ({cv_std:.2%})")
        cv_vs_test = abs(cv_mean - test_accuracy)
        if cv_std <= 0.03:
            print(f"    ✅ Low std ({cv_std:.2%}) — stable across all folds.")
        else:
            print(f"    ⚠️  Std ({cv_std:.2%}) > 0.03 — results vary across folds.")
        if cv_vs_test <= 0.05:
            print(f"    ✅ CV mean ({cv_mean:.2%}) ≈ test accuracy ({test_accuracy:.2%})")
            print(f"       Test result is trustworthy — not a lucky split.")
        else:
            print(f"    ⚠️  CV mean and test accuracy differ by {cv_vs_test:.2%}.")
        print()

        # Final test result
        print("  [ Final Test Set Result ]")
        print(f"    Test accuracy: {test_accuracy:.4f}  ({test_accuracy:.2%})")
        print()

        # Classification reports
        print("  Test Set Classification Report:")
        present_labels = sorted(y_test.unique())
        print(classification_report(
            y_test, y_test_pred,
            labels=present_labels,
            target_names=[LEAVE_DT_ACTIONS[i] for i in present_labels]
        ))

        print("  Validation Set Classification Report:")
        present_val_labels = sorted(y_val.unique())
        print(classification_report(
            y_val, y_val_pred,
            labels=present_val_labels,
            target_names=[LEAVE_DT_ACTIONS[i] for i in present_val_labels]
        ))

        # ------------------------------------------------------------------
        # Step 8: Print the tree structure
        # ------------------------------------------------------------------
        print("  Tree Structure (Root → Decision Nodes → Leaf Nodes):")
        print(export_text(self.model, feature_names=list(LEAVE_FEATURES)))

        # ------------------------------------------------------------------
        # Step 9: Save the trained model to disk
        # ------------------------------------------------------------------
        self._save()

    # =========================================================================
    # SAVE
    # =========================================================================

    def _save(self):
        """Saves the trained model to a .pkl file."""
        models_dir = os.path.join(BASE_DIR, "models")
        os.makedirs(models_dir, exist_ok=True)

        with open(self.MODEL_PATH, "wb") as f:
            pickle.dump(self.model, f)

        print(f"  Model saved → {self.MODEL_PATH}\n")

    # =========================================================================
    # LOAD
    # =========================================================================

    def load(self):
        """Loads a previously trained model from disk."""
        if not os.path.exists(self.MODEL_PATH):
            raise FileNotFoundError(
                f"No trained leave model found at:\n"
                f"  {self.MODEL_PATH}\n"
                f"Fix: run  python setup.py  first."
            )

        with open(self.MODEL_PATH, "rb") as f:
            self.model = pickle.load(f)

    # =========================================================================
    # PREDICT
    # =========================================================================

    def predict(self, features: dict) -> dict:
        """
        Uses the trained Decision Tree to predict the next routing action
        for a leave application based on its current decision state.

        Parameters:
            features (dict) — must contain all keys in LEAVE_FEATURES:
                leave_type_encoded       (int)   — 0–7
                days_requested           (int)
                has_required_attachment  (int)   — 0 or 1
                dh_decision              (int)   — 0=pending, 1=approved, 2=rejected
                hr_decision              (int)   — 0=pending, 1=approved, 2=rejected
                has_rejection_reason     (int)   — 0 or 1

        Returns:
            dict:
                routing_action_code  — int (0, 1, 2, or 3)
                routing_action_label — human-readable string
                confidence_pct       — how confident the tree is (0–100%)
        """

        if self.model is None:
            self.load()

        row = pd.DataFrame([{col: features[col] for col in LEAVE_FEATURES}])

        prediction    = self.model.predict(row)[0]
        probabilities = self.model.predict_proba(row)[0]
        confidence    = round(float(max(probabilities)) * 100, 2)

        return {
            "routing_action_code":  int(prediction),
            "routing_action_label": LEAVE_DT_ACTIONS[int(prediction)],
            "confidence_pct":       confidence,
        }
    
    # LeaveDecisionTree Visualization
    def visualize(self):
        """
        Displays the trained Leave Application Decision Tree as a diagram.
        """
        if self.model is None:
            self.load()

        plt.figure(figsize=(18, 10))
        plot_tree(
            self.model,
            feature_names=LEAVE_FEATURES,
            class_names=[LEAVE_DT_ACTIONS[i] for i in sorted(LEAVE_DT_ACTIONS.keys())],
            filled=True,
            rounded=True,
            fontsize=8
        )
        plt.title("Leave Application Decision Tree")
        plt.show()


# =============================================================================
# MAIN — Run directly to train and save the model
# =============================================================================

if __name__ == "__main__":
    ipcr = IPCRDecisionTree()
    ipcr.load()
    ipcr.visualize()

    leave = LeaveDecisionTree()
    leave.load()
    leave.visualize()